-- Massive N5 Expansion - Batch 1 (Part 1: 50 Verbs & Nouns)
-- Includes Chinese Meaning and Sentence Translation

INSERT INTO vocabulary (level, word, reading, meaning, meaning_zh, sentence, sentence_translation, sentence_translation_zh, distractors) VALUES
('N5', '行く', 'いく', 'to go', '去', '明日、京都へ（　　）。', 'I will go to Kyoto tomorrow.', '明天去京都。', ARRAY['来る', '帰る', '寝る']),
('N5', '来る', 'くる', 'to come', '来', '友達がうちに（　　）。', 'My friend will come to my house.', '朋友要来我家。', ARRAY['行く', '帰る', '遊ぶ']),
('N5', '帰る', 'かえる', 'to return home', '回/回家', '八時にうちに（　　）。', 'I will return home at eight o''clock.', '八点回家。', ARRAY['出す', '入る', '座る']),
('N5', '飲む', 'のむ', 'to drink', '喝', 'お茶を（　　）ましょう。', 'Let''s drink some tea.', '喝茶吧。', ARRAY['食べる', '吸う', '噛む']),
('N5', '食べる', 'たべる', 'to eat', '吃', '朝ご飯を（　　）ましたか。', 'Did you eat breakfast?', '吃过早饭了吗？', ARRAY['飲む', '買う', '洗う']),
('N5', '買う', 'かう', 'to buy', '买', 'デパートで靴を（　　）ました。', 'I bought shoes at the department store.', '在百货商店买了鞋。', ARRAY['売る', '貸す', '借りる']),
('N5', '見る', 'みる', 'to see', '看', '映画を（　　）に行きませんか。', 'Would you like to go see a movie?', '去不去看电影？', ARRAY['聞く', '読む', '書く']),
('N5', '聞く', 'きく', 'to hear/listen', '听', 'ラジオを（　　）ます。', 'I listen to the radio.', '听收音机。', ARRAY['見る', '言う', '呼ぶ']),
('N5', '書く', 'かく', 'to write', '写', '鉛筆で名まえを（　　）ます。', 'I write names with a pencil.', '用铅笔写名字。', ARRAY['読む', '聴く', '歩く']),
('N5', '読む', 'よむ', 'to read', '读/阅', '毎晩、本を（　　）ます。', 'I read a book every night.', '每晚读书。', ARRAY['書く', '話す', '歌う']),
('N5', '話す', 'はなす', 'to speak', '说/谈', '日本語で（　　）てください。', 'Please speak in Japanese.', '请用日语说明。', ARRAY['歌う', '笑う', '怒る']),
('N5', '言う', 'いう', 'to say', '说', '先生が（　　）ました。', 'The teacher said so.', '老师说了。', ARRAY['呼ぶ', '黙る', '笑う']),
('N5', '洗う', 'あらう', 'to wash', '洗', '手を（　　）ください。', 'Please wash your hands.', '请洗手。', ARRAY['拭く', '乾かす', '磨く']),
('N5', '遊ぶ', 'あそぶ', 'to play', '玩', '公園で（　　）ましょう。', 'Let''s play in the park.', '在公园玩吧。', ARRAY['休む', '走る', '飛ぶ']),
('N5', '会う', 'あう', 'to meet', '见面', '明日、駅で（　　）ましょう。', 'Let''s meet at the station tomorrow.', '明天在车站见面吧。', ARRAY['別れる', '消える', '入る']),
('N5', '買う', 'かう', 'to buy', '买', '新しい鞄を（　　）ました。', 'I bought a new bag.', '买了新包。', ARRAY['売る', '貸す', '直す']),
('N5', '教える', 'おしえる', 'to teach', '教', '日本語を（　　）います。', 'I am teaching Japanese.', '正在教日语。', ARRAY['習う', '見る', '知る']),
('N5', '習う', 'ならう', 'to learn', '学习/练习', 'ピアノを（　　）います。', 'I am learning the piano.', '正在学钢琴。', ARRAY['教える', '寝る', '起きる']),
('N5', '切る', 'きる', 'to cut', '剪/切', 'ハサミで紙を（　　）ます。', 'I cut paper with scissors.', '用剪刀剪纸。', ARRAY['貼る', '折る', '書く']),
('N5', '貸す', 'かす', 'to lend', '借出', 'ペンを（　　）てください。', 'Please lend me a pen.', '请借我一支笔。', ARRAY['借りる', '返す', '捨てる']),
('N5', '借りる', 'かりる', 'to borrow', '借入', '図書館で本を（　　）ました。', 'I borrowed a book from the library.', '在图书馆借了书。', ARRAY['貸す', '戻す', '送る']),
('N5', '送る', 'おくる', 'to send', '寄/送', '手紙を（　　）ます。', 'I will send a letter.', '寄信。', ARRAY['受ける', '取る', '待つ']),
('N5', '待つ', 'まつ', 'to wait', '等', '駅の前で友達を（　　）ます。', 'I will wait for my friend in front of the station.', '在车站前等朋友。', ARRAY['行く', '帰る', '動く']),
('N5', '持つ', 'もつ', 'to hold', '拿/带', '鞄を（　　）ましょうか。', 'Shall I carry your bag?', '我帮你拿包吗？', ARRAY['置く', '投げる', '拾う']),
('N5', '入る', 'はいる', 'to enter', '进入', '部屋に（　　）ます。', 'I will enter the room.', '进入房间。', ARRAY['出る', '降りる', '落ちる']),
('N5', '出る', 'でる', 'to exit', '出去', '七時にうちを（　　）ます。', 'I leave home at seven.', '七点出门。', ARRAY['入る', '登る', '乗る']),
('N5', '乗る', 'のる', 'to ride/board', '乘', 'バスに（　　）ます。', 'I will board the bus.', '坐公交车。', ARRAY['降りる', '歩く', '走る']),
('N5', '降りる', 'おりる', 'to get off', '下车', '駅でバスを（　　）ました。', 'I got off the bus at the station.', '在车站下了公交。', ARRAY['乗る', '飛ぶ', '泳ぐ']),
('N5', '散歩', 'さんぽ', 'walk/stroll', '散步', '公園を（　　）します。', 'I take a walk in the park.', '在公园散步。', ARRAY['運動', '勉強', '掃除']),
('N5', '洗濯', 'せんたく', 'laundry', '洗衣服', '日曜日に（　　）をします。', 'I do the laundry on Sundays.', '周日洗衣服。', ARRAY['料理', '掃除', '買い物']),
('N5', '掃除', 'そうじ', 'cleaning', '扫除', '毎日部屋を（　　）します。', 'I clean my room every day.', '每天打扫房间。', ARRAY['料理', '読書', '散歩']),
('N5', '電話', 'でんわ', 'phone call', '电话', '友達に（　　）をします。', 'I make a phone call to my friend.', '给朋友打电话。', ARRAY['手紙', '荷物', '写真']),
('N5', '買い物', 'かいもの', 'shopping', '买东西', 'デパートへ（　　）に行きます。', 'I go to the department store for shopping.', '去百货店买东西。', ARRAY['勉強', '散歩', '仕事']),
('N5', '仕事', 'しごと', 'work', '工作', '父は銀行で（　　）をしています。', 'My father works at a bank.', '我父亲在银行工作。', ARRAY['遊び', '趣味', '練習']),
('N5', '宿題', 'しゅくだい', 'homework', '作业', 'もう（　　）をしましたか。', 'Have you already done your homework?', '做完作业了吗？', ARRAY['テスト', '授業', '説明']),
('N5', '練習', 'れんしゅう', 'practice', '练习', 'テニスの（　　）をします。', 'I practice tennis.', '练习网球。', ARRAY['試合', '大会', '旅行']),
('N5', '勉強', 'べんきょう', 'study', '学习', '毎日三時間（　　）します。', 'I study for three hours every day.', '每天学习三小时。', ARRAY['遊ぶ', '休む', '寝る']),
('N5', '料理', 'りょうり', 'cooking', '料理/做菜', '母と（　　）を作ります。', 'I cook with my mother.', '和妈妈一起做菜。', ARRAY['食事', 'お菓子', 'ご飯']),
('N5', '食事', 'しょくじ', 'meal', '吃饭/用餐', '六時に（　　）をします。', 'I eat a meal at six.', '六点吃饭。', ARRAY['料理', '飲み物', 'おやつ']),
('N5', '旅行', 'りょこう', 'travel/trip', '旅行', '来月（　　）に行きます。', 'I will go on a trip next month.', '下个月去旅行。', ARRAY['出張', '散歩', '帰宅']),
('N5', '予約', 'よやく', 'reservation', '预约/订', 'ホテルの（　　）をしました。', 'I made a hotel reservation.', '预订了酒店。', ARRAY['約束', '計画', '相談']),
('N5', '質問', 'しつもん', 'question', '提问', '先生に（　　）があります。', 'I have a question for the teacher.', '我有问题问老师。', ARRAY['答え', '意味', '話']),
('N5', '心配', 'しんぱい', 'worry', '担心', '（　　）しないでください。', 'Please don''t worry.', '请不要担心。', ARRAY['安心', '興奮', '緊張']),
('N5', '案内', 'あんない', 'guidance/guide', '带路/引导', '町を（　　）します。', 'I will guide you through the town.', '给你带路逛逛这个镇。', ARRAY['紹介', '説明', '注意']),
('N5', '紹介', 'しょうかい', 'introduction', '介绍', '友達を（　　）します。', 'I will introduce my friend.', '介绍朋友。', ARRAY['案内', '自慢', '勧誘']),
('N5', '説明', 'せつめい', 'explanation', '说明', 'やり方を（　　）してください。', 'Please explain how to do it.', '请说明一下做法。', ARRAY['紹介', '案内', '質問']),
('N5', '注文', 'ちゅうもん', 'order', '点菜/订货', 'コーヒーを（　　）しました。', 'I ordered coffee.', '点了咖啡。', ARRAY['予約', '用意', '準備']),
('N5', '相談', 'そうだん', 'consultation', '商量', '母に（　　）ます。', 'I will consult with my mother.', '和妈妈商量。', ARRAY['約束', '喧嘩', '納得']),
('N5', '用意', 'ようい', 'preparation', '准备', '（　　）ができました。', 'Preparations are ready.', '准备好了。', ARRAY['準備', '練習', '計画']),
('N5', '準備', 'じゅんび', 'preparation', '准备', '旅行の（　　）をします。', 'I will prepare for the trip.', '做旅行的准备。', ARRAY['用意', '相談', '予約']);
