-- Massive N5 Expansion - Batch 2 (Part 1: Numbers, Counters & Time)
-- Includes Chinese Meaning and Sentence Translation

INSERT INTO vocabulary (level, word, reading, meaning, meaning_zh, sentence, sentence_translation, sentence_translation_zh, distractors) VALUES
('N5', '一', 'いち', 'one', '一/1', 'りんごを（　　）つください。', 'Please give me one apple.', '请给我一个苹果。', ARRAY['二', '三', '四']),
('N5', '二', 'に', 'two', '二/2', '切手を（　　）枚買いました。', 'I bought two stamps.', '买了两个邮票。', ARRAY['一', '三', '五']),
('N5', '三', 'さん', 'three', '三/3', '兄弟が（　　）人います。', 'I have three siblings.', '我有三个兄弟姐妹。', ARRAY['二', '四', '六']),
('N5', '四', 'し/よん', 'four', '四/4', '（　　）時に会いましょう。', 'Let''s meet at four o''clock.', '四点见。', ARRAY['三', '五', '七']),
('N5', '五', 'ご', 'five', '五/5', '手を（　　）分洗います。', 'I wash my hands for five minutes.', '洗五分钟手。', ARRAY['六', '四', '八']),
('N5', '六', 'ろく', 'six', '六/6', '（　　）ヶ月勉強しました。', 'I studied for six months.', '学习了六个月。', ARRAY['五', '七', '九']),
('N5', '七', 'しち/なな', 'seven', '七/7', '（　　）時に起きます。', 'I wake up at seven o''clock.', '七点起床。', ARRAY['六', '八', '十']),
('N5', '八', 'はち', 'eight', '八/8', '（　　）月はとても暑いです。', 'August is very hot.', '八月非常热。', ARRAY['七', '九', '六']),
('N5', '九', 'きゅう/く', 'nine', '九/9', '（　　）時まで働きます。', 'I work until nine o''clock.', '工作到九点。', ARRAY['八', '十', '一']),
('N5', '十', 'じゅう', 'ten', '十/10', '（　　）日で終わります。', 'It will finish in ten days.', '十天后结束。', ARRAY['九', '十一', '一']),
('N5', '百', 'ひゃく', 'hundred', '百/100', 'このペンは（　　）円です。', 'This pen is 100 yen.', '这个笔100日元。', ARRAY['千', '万', '一']),
('N5', '千', 'せん', 'thousand', '千/1000', '（　　）円貸してください。', 'Please lend me 1000 yen.', '请借我1000日元。', ARRAY['万', '百', '十']),
('N5', '万', 'まん', 'ten thousand', '万/10000', 'カメラは三（　　）円でした。', 'The camera was 30,000 yen.', '照相机三万日元。', ARRAY['千', '百', '一']),
('N5', '円', 'えん', 'yen', '日元', 'これはいくら（　　）ですか。', 'How many yen is this?', '这个多少日元？', ARRAY['ドル', 'ユーロ', 'ポンド']),
('N5', '時間', 'じかん', 'time/hour', '时间/小时', '（　　）がありますか。', 'Do you have time?', '有时间吗？', ARRAY['時計', '約束', '用事']),
('N5', '時', 'じ', 'o''clock', '点/点钟', '今、何（　　）ですか。', 'What time is it now?', '现在几点？', ARRAY['分', '秒', '日']),
('N5', '分', 'ふん', 'minute', '分/分钟', '地下鉄で三（　　）です。', 'It''s three minutes by subway.', '坐地铁三分钟。', ARRAY['時', '日', '回']),
('N5', '半', 'はん', 'half (past)', '半', '九時（　　）に出発します。', 'We will depart at half-past nine.', '九点半出发。', ARRAY['分', '時', '前']),
('N5', '日', 'ひ/にち', 'day', '日/天', 'いい（　　）ですね。', 'It''s a nice day, isn''t it?', '天气真好。', ARRAY['月', '年', '週']),
('N5', '一日', 'ついたち', '1st of the month', '一号', '（　　）は日曜日です。', 'The 1st is Sunday.', '一号是周日。', ARRAY['一日(いちにち)', '二日', '三日']),
('N5', '二日', 'ふつか', '2nd of the month', '二号/两天', '（　　）休みます。', 'I will rest for two days.', '休息两天。', ARRAY['三日', '一日', '四日']),
('N5', '月曜日', 'げつようび', 'Monday', '周一', '（　　）から仕事です。', 'Work starts from Monday.', '从周一开始工作。', ARRAY['火曜日', '日曜日', '金曜日']),
('N5', '火曜日', 'かようび', 'Tuesday', '周二', '（　　）は休みです。', 'Tuesday is a holiday.', '周二休息。', ARRAY['水曜日', '月曜日', '土曜日']),
('N5', '水曜日', 'すいようび', 'Wednesday', '周三', '（　　）に会いましょう。', 'Let''s meet on Wednesday.', '周三见面吧。', ARRAY['木曜日', '火曜日', '金曜日']),
('N5', '木曜日', 'もくようび', 'Thursday', '周四', '（　　）は雨でした。', 'It was raining on Thursday.', '周四下雨了。', ARRAY['金曜日', '水曜日', '月曜日']),
('N5', '金曜日', 'きんようび', 'Friday', '周五', '（　　）の夜に飲みます。', 'I will drink on Friday night.', '周五晚上喝酒。', ARRAY['土曜日', '木曜日', '水曜日']),
('N5', '土曜日', 'どようび', 'Saturday', '周六', '（　　）は買い物に行きます。', 'I go shopping on Saturday.', '周六去买东西。', ARRAY['日曜日', '金曜日', '月曜日']),
('N5', '日曜日', 'にちようび', 'Sunday', '周日', '（　　）はゆっくりします。', 'I will relax on Sunday.', '周日好好休息。', ARRAY['土曜日', '月曜日', '火曜日']),
('N5', '今', 'いま', 'now', '现在', '（　　）何時ですか。', 'What time is it now?', '现在几点？', ARRAY['後で', '前', '次']),
('N5', '前', 'まえ', 'before/front', '前/以前', '駅の（　　）で待ちます。', 'I will wait in front of the station.', '在车站前等。', ARRAY['後', '横', '上']),
('N5', '後', 'あと', 'after/later', '后/以后', '（　　）で話をしましょう。', 'Let''s talk later.', '等会儿再说。', ARRAY['前', '先', '今']),
('N5', '毎日', 'まいにち', 'every day', '每天', '（　　）日本語を勉強します。', 'I study Japanese every day.', '每天学习日语。', ARRAY['毎週', '毎月', '毎年']),
('N5', '毎週', 'まいしゅう', 'every week', '每周', '（　　）テニスをします。', 'I play tennis every week.', '每周打网球。', ARRAY['毎日', '毎月', '毎年']),
('N5', '毎月', 'まいつき', 'every month', '每月', '（　　）国へ帰ります。', 'I return to my country every month.', '每月回国。', ARRAY['毎日', '毎週', '毎年']),
('N5', '毎年', 'まいねん', 'every year', '每年', '（　　）旅行に行きます。', 'I go on a trip every year.', '每年去旅行。', ARRAY['毎日', '毎週', '毎月']),
('N5', '朝', 'あさ', 'morning', '早上', '（　　）ご飯を食べました。', 'I ate breakfast.', '吃了早饭。', ARRAY['昼', '晩', '夜']),
('N5', '昼', 'ひる', 'daytime/noon', '中午', '（　　）休みは一時からです。', 'Lunch break starts from one o''clock.', '午休一点开始。', ARRAY['朝', '晩', '夕方']),
('N5', '晩', 'ばん', 'evening', '晚上', '（　　）ご飯は何ですか。', 'What is for dinner?', '晚饭吃什么？', ARRAY['朝', '昼', '夜']),
('N5', '夜', 'よる', 'night', '夜/晚上', '（　　）は早く寝ます。', 'I go to bed early at night.', '晚上早睡。', ARRAY['朝', '昼', '夕方']),
('N5', '夕方', 'ゆうがた', 'evening/dusk', '傍晚', '（　　）から雨が降ります。', 'It will rain from early evening.', '从傍晚开始下雨。', ARRAY['朝', '昼', '夜']),
('N5', '今日', 'きょう', 'today', '今天', '（　　）はいい天気です。', 'Today is nice weather.', '今天天气不错。', ARRAY['明日', '昨日', '毎日']),
('N5', '明日', 'あした', 'tomorrow', '明天', '（　　）また会いましょう。', 'Let''s meet again tomorrow.', '明天见。', ARRAY['今日', '昨日', '明後日']),
('N5', '昨日', 'きのう', 'yesterday', '昨天', '（　　）は休みでした。', 'Yesterday was a holiday.', '昨天休息。', ARRAY['今日', '明日', '一昨日']),
('N5', '明後日', 'あさって', 'day after tomorrow', '后天', '（　　）から旅行です。', 'I''m going on a trip the day after tomorrow.', '从后天开始旅行。', ARRAY['明日', '昨日', '今日']),
('N5', '一昨日', 'おととい', 'day before yesterday', '前天', '（　　）は雨でした。', 'It was raining the day before yesterday.', '前天下雨了。', ARRAY['昨日', '今日', '明日']),
('N5', '今週', 'こんしゅう', 'this week', '本周', '（　　）は忙しいです。', 'I am busy this week.', '这周很忙。', ARRAY['来週', '先週', '毎週']),
('N5', '来週', 'らいしゅう', 'next week', '下周', '（　　）テストがあります。', 'There is a test next week.', '下周有考试。', ARRAY['今週', '先週', '再来週']),
('N5', '先週', 'せんしゅう', 'last week', '上周', '（　　）京都へ行きました。', 'I went to Kyoto last week.', '上周去了京都。', ARRAY['今週', '来週', '再来週']),
('N5', '今月', 'こんげつ', 'this month', '本月', '（　　）は休みが多いです。', 'There are many holidays this month.', '这个月假多。', ARRAY['来月', '先月', '毎月']),
('N5', '来月', 'らいげつ', 'next month', '下月', '（　　）日本へ行きます。', 'I will go to Japan next month.', '下个月去日本。', ARRAY['今月', '先月', '再来月']),
('N5', '先月', 'せんげつ', 'last month', '上月', '（　　）は寒かったです。', 'It was cold last month.', '上个月很冷。', ARRAY['今月', '来月', '再来月']);
