-- Massive N5 Expansion - Batch 4 (Part 1: Activities & Social Verbs)
-- Includes Chinese Meaning and Sentence Translation

INSERT INTO vocabulary (level, word, reading, meaning, meaning_zh, sentence, sentence_translation, sentence_translation_zh, distractors) VALUES
('N5', '会う', 'あう', 'to meet', '见面/遇见', '駅で友達に（　　）ました。', 'I met a friend at the station.', '在车站见到了朋友。', ARRAY['貸す', '待つ', '呼ぶ']),
('N5', '遊ぶ', 'あそぶ', 'to play/hang out', '玩/游戏', '休みの日は友達と（　　）ます。', 'I hang out with friends on holidays.', '休息日和朋友玩。', ARRAY['働く', '休む', '忙しい']),
('N5', '洗う', 'あらう', 'to wash', '洗', 'ご飯を食べる前に手を（　　）ます。', 'I wash my hands before eating.', '吃饭前洗手。', ARRAY['拭く', '磨く', '乾かす']),
('N5', '歌う', 'うたう', 'to sing', '唱歌', 'みんなで歌を（　　）ましょう。', 'Let''s sing songs together.', '大家一起唱歌吧。', ARRAY['踊る', '聞く', '話す']),
('N5', '引く', 'ひく', 'to pull/look up', '拉/查', '辞書を（　　）て勉強します。', 'I look up in the dictionary and study.', '查词典学习。', ARRAY['押す', '引く(pull)', '持つ']),
('N5', '弾く', 'ひく', 'to play (instrument)', '弹（乐器）', 'ピアノを（　　）ことができます。', 'I can play the piano.', '我会弹钢琴。', ARRAY['歌う', '吹く', '聞く']),
('N5', '泳ぐ', 'およぐ', 'to swim', '游泳', '夏はプールで（　　）ます。', 'I swim in the pool in summer.', '夏天在池里游泳。', ARRAY['走る', '飛ぶ', '登る']),
('N5', '走る', 'はしる', 'to run', '跑', '毎朝公園を（　　）ます。', 'I run in the park every morning.', '每天早上在公园跑。', ARRAY['歩く', '飛ぶ', '泳ぐ']),
('N5', '歩く', 'あるく', 'to walk', '走/步行', '駅から家まで（　　）ます。', 'I walk from the station to my house.', '从车站走回家。', ARRAY['走る', '乗る', '飛ぶ']),
('N5', '飛ぶ', 'とぶ', 'to fly/jump', '飞/跳', '鳥が空を（　　）ています。', 'Birds are flying in the sky.', '鸟在天上飞。', ARRAY['泳ぐ', '這う', '歩く']),
('N5', '座る', 'すわる', 'to sit', '坐', '椅子に（　　）て待ってください。', 'Please sit on the chair and wait.', '请坐椅子等。', ARRAY['立つ', '寝る', '起きる']),
('N5', '立つ', 'たつ', 'to stand', '站/起立', 'そこに（　　）てください。', 'Please stand there.', '请战在那。', ARRAY['座る', '寝る', '走る']),
('N5', '寝る', 'ねる', 'to sleep', '睡觉', '夜十時に（　　）ます。', 'I go to bed at 10 PM.', '晚上十点睡觉。', ARRAY['起きる', '休む', '走る']),
('N5', '起きる', 'おきる', 'to wake up/get up', '起床', '朝六時に（　　）ます。', 'I wake up at 6 AM.', '早上六点起床。', ARRAY['寝る', '眠る', '伏せる']),
('N5', '休む', 'やすむ', 'to rest/take a day off', '休息/请假', '今日は会社を（　　）ます。', 'I am taking a day off from work today.', '今天公司请假。', ARRAY['働く', '忙しい', '遊ぶ']),
('N5', '笑う', 'わらう', 'to laugh/smile', '笑', 'みんなで（　　）ました。', 'Everyone laughed.', '大家笑了。', ARRAY['泣く', '怒る', '歌う']),
('N5', '泣く', 'なく', 'to cry', '哭', 'おなかが空いて赤ん坊が（　　）ています。', 'The baby is crying because they are hungry.', '宝宝饿哭了。', ARRAY['笑う', '歌う', '踊る']),
('N5', '怒る', 'おこる', 'to get angry', '生气', '先生を（　　）せてしまいました。', 'I made the teacher angry.', '惹老师生气了。', ARRAY['笑う', '喜ぶ', '楽しむ']),
('N5', '忘れる', 'わすれる', 'to forget', '忘记', '傘を（　　）ました。', 'I forgot my umbrella.', '忘了带伞。', ARRAY['覚える', '知る', 'わかる']),
('N5', '覚える', 'おぼえる', 'to remember/memorize', '记住', '漢字を三つ（　　）ました。', 'I memorized three Kanji.', '记住了三个汉字。', ARRAY['忘れる', '習う', '見る']),
('N5', '晴れ', 'はれ', 'sunny weather', '晴天', '今日は（　　）ですね。', 'It''s sunny today, isn''t it?', '今天天气真晴朗。', ARRAY['雨', '曇り', '雪']),
('N5', '雨', 'あめ', 'rain', '雨/下雨', '（　　）が降っています。', 'It is raining.', '下雨了。', ARRAY['雪', '風', '晴れ']),
('N5', '曇り', 'くもり', 'cloudy weather', '阴天', '（　　）の日は涼しいです。', 'It''s cool on cloudy days.', '阴天很凉快。', ARRAY['晴れ', '雨', '風']),
('N5', '雪', 'ゆき', 'snow', '雪/下雪', '山に（　　）が降りました。', 'It snowed on the mountain.', '山上下雪了。', ARRAY['雨', '氷', '風']),
('N5', '風', 'かぜ', 'wind', '风', '今日は（　　）が強いです。', 'The wind is strong today.', '今天风很大。', ARRAY['雨', '雪', '雷']),
('N5', '暑い', 'あつい', 'hot (weather)', '热', '夏は（　　）ですね。', 'Summer is hot, isn''t it?', '夏天很热。', ARRAY['寒い', '涼しい', '暖かい']),
('N5', '寒い', 'さむい', 'cold (weather)', '冷', '冬は（　　）です。', 'Winter is cold.', '冬天很冷。', ARRAY['暑い', '暖かい', '涼しい']),
('N5', '暖かい', 'あたたかい', 'warm (weather)', '暖和', '春は（　　）から好きです。', 'I like spring because it''s warm.', '因为春天很暖和，所以我喜欢。', ARRAY['寒い', '冷たい', '涼しい']),
('N5', '涼しい', 'すずしい', 'cool (weather)', '凉爽', '（　　）風が吹いています。', 'A cool breeze is blowing.', '吹着凉爽的风。', ARRAY['暑い', '暖かい', '寒い']),
('N5', '天', 'てん', 'heaven/sky', '天/天空', '（　　）気がいいです。', 'The weather is good.', '天气很好。', ARRAY['地', '心', '体']),
('N5', '体', 'からだ', 'body', '身体', '（　　）を大切にしてください。', 'Please take care of your body.', '请保重身体。', ARRAY['心', '頭', '顔']),
('N5', '頭', 'あたま', 'head', '头', '（　　）が痛いです。', 'My head hurts.', '头痛。', ARRAY['体', '目', '手']),
('N5', '顔', 'かお', 'face', '脸', '（　　）を洗います。', 'I wash my face.', '洗脸。', ARRAY['耳', '足', '頭']),
('N5', '目', 'め', 'eye', '眼睛', '（　　）が大きいです。', 'His eyes are big.', '眼睛很大。', ARRAY['鼻', '口', '耳']),
('N5', '耳', 'みみ', 'ear', '耳朵', '（　　）が聞こえません。', 'I can''t hear with my ears.', '耳朵听不清楚。', ARRAY['目', '口', '足']),
('N5', '口', 'くち', 'mouth', '嘴', '（　　）を大きく開けてください。', 'Please open your mouth wide.', '请张大嘴巴。', ARRAY['目', '耳', '鼻']),
('N5', '鼻', 'はな', 'nose', '鼻子', '（　　）が高いですね。', 'You have a high nose.', '鼻子真挺。', ARRAY['口', '足', '首']),
('N5', '手', 'て', 'hand', '手', '（　　）がきれいです。', 'Her hands are beautiful.', '手很漂亮。', ARRAY['足', '首', '指']),
('N5', '指', 'ゆび', 'finger', '手指', '（　　）が長いです。', 'His fingers are long.', '手指很长。', ARRAY['手', '足', '爪']),
('N5', '足', 'あし', 'foot/leg', '脚/腿', '（　　）が痛くて歩けません。', 'My legs hurt and I can''t walk.', '腿痛走不了路。', ARRAY['手', '頭', '心']),
('N5', '首', 'くび', 'neck', '脖子', '（　　）にマフラーを巻きます。', 'I wrap a scarf around my neck.', '脖子上围着围巾。', ARRAY['手', '足', '頭']),
('N5', '肩', 'かた', 'shoulder', '肩膀', '（　　）が凝りました。', 'My shoulders are stiff.', '肩膀酸。', ARRAY['首', '腰', '背中']),
('N5', '背中', 'せなか', 'back', '背', '（　　）が痛いです。', 'My back hurts.', '背痛。', ARRAY['腹', '肩', '首']),
('N5', '腹', 'はら', 'stomach', '肚子/腹部', 'お（　　）が空きました。', 'My stomach is empty (I am hungry).', '肚子饿了。', ARRAY['胸', '背中', '足']),
('N5', '胸', 'むね', 'chest', '胸', '（　　）を張ってください。', 'Please puff out your chest.', '挺起胸膛。', ARRAY['腹', '背中', '肩']),
('N5', '声', 'こえ', 'voice', '声音', '大きい（　　）で話してください。', 'Please speak in a loud voice.', '请大声点。', ARRAY['音', '曲', '歌']),
('N5', '音', 'おと', 'sound', '音/声音', '（　　）を小さくしてください。', 'Please lower the sound.', '请把音量调小。', ARRAY['声', '光', '色']),
('N5', '色', 'いろ', 'color', '颜色', '（　　）鉛筆を貸してください。', 'Please lend me colored pencils.', '请借我彩色铅笔。', ARRAY['形', '味', '音']),
('N5', '形', 'かたち', 'shape', '形状', '面白い（　　）ですね。', 'It''s an interesting shape, isn''t it?', '形状很有趣。', ARRAY['色', '味', '重さ']),
('N5', '味', 'あじ', 'taste', '味道', 'いい（　　）がします。', 'It has a good taste.', '味道很好。', ARRAY['形', '音', '臭い']);
