-- Massive N5 Expansion - Batch 1 (Part 2: 50 Nouns & Family)
-- Includes Chinese Meaning and Sentence Translation

INSERT INTO vocabulary (level, word, reading, meaning, meaning_zh, sentence, sentence_translation, sentence_translation_zh, distractors) VALUES
('N5', '家族', 'かぞく', 'family', '家人/家族', '（　　）は日本にいます。', 'My family is in Japan.', '家人在日本。', ARRAY['友達', '先生', '学生']),
('N5', '両親', 'りょうしん', 'parents', '父母/双亲', '（　　）に手紙を書きます。', 'I will write a letter to my parents.', '给父母写信。', ARRAY['兄弟', '姉妹', '祖父母']),
('N5', '兄弟', 'きょうだい', 'siblings', '兄弟姐妹', '（　　）は何人ですか。', 'How many siblings do you have?', '你有几个兄弟姐妹？', ARRAY['家族', '親子', '夫婦']),
('N5', '父', 'ちち', 'father (my)', '（我）父亲', '（　　）は会社員です。', 'My father is a company employee.', '我父亲是公司职员。', ARRAY['母', '兄', '弟']),
('N5', '母', 'はは', 'mother (my)', '（我）母亲', '（　　）は料理が上手です。', 'My mother is good at cooking.', '我妈妈做菜很好吃。', ARRAY['父', '姉', '妹']),
('N5', '兄', 'あに', 'older brother (my)', '（我）哥哥', '（　　）は大学生です。', 'My older brother is a university student.', '我哥哥是大学生。', ARRAY['弟', '姉', '妹']),
('N5', '姉', 'あね', 'older sister (my)', '（我）姐姐', '（　　）は結婚しています。', 'My older sister is married.', '我姐姐结婚了。', ARRAY['妹', '兄', '弟']),
('N5', '弟', 'おとうと', 'younger brother (my)', '（我）弟弟', '（　　）は高校生です。', 'My younger brother is a high school student.', '我弟弟是高中生。', ARRAY['兄', '姉', '妹']),
('N5', '妹', 'いもうと', 'younger sister (my)', '（我）妹妹', '（　　）は中学生です。', 'My younger sister is a junior high student.', '我妹妹是初中生。', ARRAY['姉', '兄', '弟']),
('N5', '学校', 'がっこう', 'school', '学校', '明日（　　）へ行きます。', 'I am going to school tomorrow.', '明天去学校。', ARRAY['銀行', '病院', '公園']),
('N5', '大学', 'だいがく', 'university', '大学', '（　　）で日本文学を勉強しました。', 'I studied Japanese literature at university.', '在大学学习了日本文学。', ARRAY['高校', '中学', '小学校']),
('N5', '先生', 'せんせい', 'teacher', '老师', '（　　）に質問しました。', 'I asked the teacher a question.', '问了老师问题。', ARRAY['学生', '会社員', '医者']),
('N5', '学生', 'がくせい', 'student', '学生', '私は（　　）です。', 'I am a student.', '我是学生。', ARRAY['先生', '留学生', '校長']),
('N5', '留学生', 'りゅうがくせい', 'international student', '留学生', '彼はアメリカからの（　　）です。', 'He is an international student from America.', '他是来自美国的留学生。', ARRAY['大学生', '小学生', '研究生']),
('N5', '友達', 'ともだち', 'friend', '朋友', '（　　）と遊びます。', 'I play with my friend.', '和朋友玩。', ARRAY['家族', '先生', '隣人']),
('N5', '家', 'いえ', 'house/home', '房子/家', '（　　）で晩ご飯を食べます。', 'I eat dinner at home.', '在家吃晚饭。', ARRAY['庭', '部屋', '台所']),
('N5', '部屋', 'へや', 'room', '房间', '私の（　　）は狭いです。', 'My room is small.', '我的房间很小。', ARRAY['店', '教室', '事務所']),
('N5', '庭', 'にわ', 'garden/yard', '院子', '（　　）に花が咲いています。', 'Flowers are blooming in the garden.', '院子里开着花。', ARRAY['池', '森', '山']),
('N5', '台所', 'だいどころ', 'kitchen', '厨房', '母は（　　）にいます。', 'Mother is in the kitchen.', '妈妈在厨房。', ARRAY['浴室', '玄関', '廊下']),
('N5', '玄関', 'げんかん', 'entrance/hallway', '玄关/门口', '（　　）で靴を脱ぎます。', 'I take off my shoes at the entrance.', '在玄关脱鞋。', ARRAY['窓', '壁', '床']),
('N5', '窓', 'まど', 'window', '窗户', '（　　）を開けてください。', 'Please open the window.', '请开窗。', ARRAY['ドア', 'カーテン', '鍵']),
('N5', '椅子', 'いす', 'chair', '椅子', '（　　）に座ってください。', 'Please sit on the chair.', '请坐椅子。', ARRAY['机', 'ベッド', 'ソファー']),
('N5', '机', 'つくえ', 'desk/table', '桌子', '（　　）の上に本があります。', 'There is a book on the desk.', '桌子上有书。', ARRAY['棚', '箱', '鞄']),
('N5', '冷蔵庫', 'れいぞうこ', 'refrigerator', '冰箱', '（　　）に牛乳があります。', 'There is milk in the refrigerator.', '冰箱里有牛奶。', ARRAY['洗濯機', '掃除機', '電話']),
('N5', '時計', 'とけい', 'clock/watch', '表/钟', '（　　）はどこですか。', 'Where is the clock?', '钟在哪？', ARRAY['眼鏡', '鍵', '財布']),
('N5', '眼鏡', 'めがね', 'glasses', '眼镜', '（　　）をかけています。', 'I am wearing glasses.', '戴着眼镜。', ARRAY['帽子', '指輪', '時計']),
('N5', '財布', 'さいふ', 'wallet', '钱包', '（　　）を忘れました。', 'I forgot my wallet.', '忘了钱包。', ARRAY['鞄', '傘', '鍵']),
('N5', '鞄', 'かばん', 'bag', '包/书包', 'この（　　）は重いです。', 'This bag is heavy.', '这个书包很重。', ARRAY['財布', '箱', '服']),
('N5', '鍵', 'かぎ', 'key', '钥匙', '（　　）をかけました。', 'I locked the door (put the key).', '锁了（插了钥匙）。', ARRAY['窓', 'ドア', '門']),
('N5', '切手', 'きって', 'stamp', '邮票', '（　　）を貼ってください。', 'Please put on a stamp.', '请贴邮票。', ARRAY['封筒', '葉書', '地図']),
('N5', '封筒', 'ふうとう', 'envelope', '信封', '（　　）に住所を書きます。', 'I write the address on the envelope.', '在信封上写地址。', ARRAY['切手', '便箋', '荷物']),
('N5', '葉書', 'はがき', 'postcard', '明信片', '友達に（　　）を出します。', 'I will send a postcard to my friend.', '给朋友寄明信片。', ARRAY['手紙', '本', '雑誌']),
('N5', '手紙', 'てがみ', 'letter', '信', '国に（　　）を書きます。', 'I will write a letter to my country.', '给家里写信。', ARRAY['電話', '写真', '荷物']),
('N5', '写真', 'しゃしん', 'photo', '照片', '（　　）を撮りましょう。', 'Let''s take a photo.', '拍张照片吧。', ARRAY['絵', '映画', '漫画']),
('N5', '本', 'ほん', 'book', '书', '（　　）を読みました。', 'I read a book.', '看了书。', ARRAY['辞書', '雑誌', '新聞']),
('N5', '辞書', 'じしょ', 'dictionary', '词典/字典', '（　　）を引きます。', 'I look up in the dictionary.', '查词典。', ARRAY['教科書', '小説', '地図']),
('N5', '雑誌', 'ざっし', 'magazine', '杂志', '（　　）を読みます。', 'I read magazines.', '看杂志。', ARRAY['新聞', '本', '漫画']),
('N5', '新聞', 'しんぶん', 'newspaper', '报纸', '毎朝（　　）を読みます。', 'I read the newspaper every morning.', '每天早上读报。', ARRAY['雑誌', '本', '日記']),
('N5', '鉛筆', 'えんぴつ', 'pencil', '铅笔', '（　　）を貸してください。', 'Please lend me a pencil.', '请借我铅笔。', ARRAY['万年筆', 'ボールペン', '筆']),
('N5', '万年筆', 'まんねんひつ', 'fountain pen', '钢笔', '父に（　　）をもらいました。', 'I received a fountain pen from my father.', '从父亲那里得到了钢笔。', ARRAY['鉛筆', '消しゴム', '定規']),
('N5', 'ボールペン', 'ぼーるぺん', 'ballpoint pen', '圆珠笔', '（　　）で書きます。', 'I write with a ballpoint pen.', '用圆珠笔写。', ARRAY['鉛筆', '万年筆', '毛筆']),
('N5', '消しゴム', 'けしごむ', 'eraser', '橡皮擦', '（　　）はありますか。', 'Do you have an eraser?', '有橡皮吗？', ARRAY['定規', '鉛筆', '筆箱']),
('N5', '定規', 'じょうぎ', 'ruler', '尺子', '（　　）を使います。', 'I use a ruler.', '用尺子。', ARRAY['消しゴム', '鉛筆', '鋏']),
('N5', '地図', 'ちず', 'map', '地图', '（　　）を見せてください。', 'Please show me the map.', '请给我看地图。', ARRAY['絵', '写真', '本']),
('N5', 'お菓子', 'おかし', 'sweets/snack', '点心/零食', '（　　）を食べます。', 'I eat sweets.', '吃零食。', ARRAY['ご飯', '果物', '野菜']),
('N5', '果物', 'くだもの', 'fruit', '水果', '（　　）が好きです。', 'I like fruit.', '喜欢水果。', ARRAY['野菜', '肉', '魚']),
('N5', '野菜', 'やさい', 'vegetables', '蔬菜', '（　　）を食べましょう。', 'Let''s eat vegetables.', '吃蔬菜吧。', ARRAY['果物', '菓子', '料理']),
('N5', '肉', 'にく', 'meat', '肉', '（　　）を食べません。', 'I don''t eat meat.', '我不吃肉。', ARRAY['魚', '野菜', '果物']),
('N5', '魚', 'さかな', 'fish', '鱼', '（　　）が好きです。', 'I like fish.', '喜欢鱼。', ARRAY['肉', '虫', '鳥']),
('N5', '卵', 'たまご', 'egg', '蛋/鸡蛋', '（　　）を食べました。', 'I ate an egg.', '吃了鸡蛋。', ARRAY['牛乳', '豆腐', '海苔']);
