-- Massive N5 Expansion - Batch 3 (Part 2: na-adjectives & Colors)
-- Includes Chinese Meaning and Sentence Translation

INSERT INTO vocabulary (level, word, reading, meaning, meaning_zh, sentence, sentence_translation, sentence_translation_zh, distractors) VALUES
('N5', '親切', 'しんせつ', 'kind', '亲切/亲切人', '（　　）な人に会いました。', 'I met a kind person.', '遇到了亲切的人。', ARRAY['不親切', '冷たい', '便利']),
('N5', '静か', 'しずか', 'quiet', '安静', '夜は（　　）ですね。', 'It''s quiet at night, isn''t it?', '晚上很安静。', ARRAY['賑やか', 'うるさい', '元気']),
('N5', '賑やか', 'にぎやか', 'lively/bustling', '热闹', 'この町はとても（　　）です。', 'This town is very bustling.', '这个镇非常热闹。', ARRAY['静か', '広い', '狭い']),
('N5', '有名', 'ゆうめい', 'famous', '有名', 'ここは（　　）な公園です。', 'This is a famous park.', '这是非常有名的公园。', ARRAY['無名', '上手', '下手']),
('N5', '不便', 'ふべん', 'inconvenient', '不便', '車がないと（　　）です。', 'It is inconvenient without a car.', '没车的话很不方便。', ARRAY['便利', '自由', '不自由']),
('N5', '元気', 'げんき', 'healthy/energetic', '精神/健康', 'お（　　）ですか。', 'Are you healthy/well?', '你好吗？/身体好吗？', ARRAY['病気', '静か', '暇']),
('N5', '暇', 'ひま', 'free/not busy', '有空/闲', '明日は（　　）です。', 'I am free tomorrow.', '明天有空。', ARRAY['忙しい', '元気', '上手']),
('N5', '大変', 'たいへん', 'tough/difficult', '辛苦/够受的', '仕事は（　　）ですか。', 'Is work tough?', '工作辛苦吗？', ARRAY['簡単', '楽', '面白い']),
('N5', '楽', 'らく', 'easy/comfortable', '轻松', 'この靴は（　　）です。', 'These shoes are comfortable.', '这双鞋很轻松。', ARRAY['大変', '難しい', '重い']),
('N5', '色', 'いろ', 'color', '颜色', 'どんな（　　）が好きですか。', 'What kind of color do you like?', '喜欢什么样的颜色？', ARRAY['形', '味', '音']),
('N5', '白い', 'しろい', 'white', '白色', '（　　）シャツを着ています。', 'I am wearing a white shirt.', '穿着白衬衫。', ARRAY['黒い', '赤い', '青い']),
('N5', '黒い', 'くろい', 'black', '黑色', '（　　）鞄を持っています。', 'I am carrying a black bag.', '拿着黑包。', ARRAY['白い', '青い', '黄色い']),
('N5', '赤い', 'あかい', 'red', '红色', '（　　）りんごを食べました。', 'I ate a red apple.', '吃了红苹果。', ARRAY['青い', '黄色い', '白い']),
('N5', '青い', 'あおい', 'blue', '蓝色', '（　　）海が見えます。', 'I can see the blue sea.', '能看到蓝海。', ARRAY['赤い', '黒い', '白い']),
('N5', '黄色い', 'きいろい', 'yellow', '黄色', '（　　）花が咲きました。', 'A yellow flower bloomed.', '开了一朵黄花。', ARRAY['赤い', '青い', '黒い']),
('N5', '茶色い', 'ちゃいろい', 'brown', '茶色/褐色', '（　　）靴を履いています。', 'I am wearing brown shoes.', '穿着褐色的鞋。', ARRAY['黒い', '白い', '青い']),
('N5', '緑', 'みどり', 'green', '绿色', '（　　）が多い町です。', 'It''s a town with lots of greenery.', '是个绿化很多的镇。', ARRAY['赤', '青', '黄']),
('N5', '紫', 'むらさき', 'purple', '紫色', '（　　）の服が好きです。', 'I like purple clothes.', '喜欢紫色的衣服。', ARRAY['黄色', '白', '黒']),
('N5', '灰色', 'はいいろ', 'grey', '灰色', '（　　）の空ですね。', 'It''s a grey sky, isn''t it?', '天灰蒙蒙的。', ARRAY['青空', '白', '黒']),
('N5', '金', 'きん', 'gold', '金', '（　　）の時計をしています。', 'He is wearing a gold watch.', '戴着金表。', ARRAY['銀', '銅', '鉄']),
('N5', '銀', 'ぎん', 'silver', '银', '（　　）色のペンです。', 'It''s a silver pen.', '是银色的笔。', ARRAY['金', '鉄', '鉛']),
('N5', '服', 'ふく', 'clothes', '衣服', '新しい（　　）を買いました。', 'I bought new clothes.', '买了新衣服。', ARRAY['靴', '鞄', '帽子']),
('N5', '靴', 'くつ', 'shoes', '鞋', '（　　）を脱いでください。', 'Please take off your shoes.', '请脱鞋。', ARRAY['靴下', '服', 'ズボン']),
('N5', '靴下', 'くつした', 'socks', '袜子', '（　　）を履いています。', 'I am wearing socks.', '穿着袜子。', ARRAY['靴', '手袋', '帽子']),
('N5', '帽子', 'ぼうし', 'hat/cap', '帽子', '（　　）をかぶっています。', 'I am wearing a hat.', '戴着帽子。', ARRAY['眼鏡', '時計', '指輪']),
('N5', 'ズボン', 'ずぼん', 'pants/trousers', '裤子', '青い（　　）を買いました。', 'I bought blue pants.', '买了蓝色裤子。', ARRAY['スカート', 'シャツ', 'コート']),
('N5', 'スカート', 'すかーと', 'skirt', '裙子', '（　　）を履いています。', 'She is wearing a skirt.', '穿着裙子。', ARRAY['ズボン', '服', '靴']),
('N5', 'シャツ', 'しゃつ', 'shirt', '衬衫', '白い（　　）を着ます。', 'I wear a white shirt.', '穿白衬衫。', ARRAY['コート', 'セーター', '帽子']),
('N5', 'コート', 'こーと', 'coat', '大衣/外套', '冬は（　　）を着ます。', 'I wear a coat in winter.', '冬天穿大衣。', ARRAY['シャツ', 'Ｔシャツ', 'スカート']),
('N5', 'セーター', 'せーたー', 'sweater', '毛衣', '（　　）を編みます。', 'I knit a sweater.', '织毛衣。', ARRAY['シャツ', 'ズボン', '靴下']),
('N5', 'Ｔシャツ', 'てぃーしゃつ', 'T-shirt', 'T恤', '夏は（　　）がいいです。', 'T-shirts are good in summer.', '夏天T恤好。', ARRAY['コート', 'セーター', '服']),
('N5', '下着', 'したぎ', 'underwear', '内衣', '（　　）を洗いました。', 'I washed the underwear.', '洗了内衣。', ARRAY['上着', '服', '靴']),
('N5', '上着', 'うわぎ', 'jacket/outerwear', '上衣/外套', '（　　）を脱ぎました。', 'I took off my jacket.', '脱了外套。', ARRAY['下着', '服', 'ズボン']),
('N5', '背広', 'せびろ', 'business suit', '西装', '毎日（　　）を着ます。', 'I wear a business suit every day.', '每天穿西装。', ARRAY['Ｔシャツ', 'ズボン', '制服']),
('N5', '制服', 'せいふく', 'uniform', '制服', '学校の（　　）です。', 'It is a school uniform.', '是学校制服。', ARRAY['背広', '服', '靴']),
('N5', 'ポケット', 'ぽけっと', 'pocket', '口袋', '（　　）に手を入れています。', 'He has his hands in his pockets.', '手插在口袋里。', ARRAY['鞄', '箱', '部屋']),
('N5', 'ボタン', 'ぼたん', 'button', '纽扣', '（　　）が取れました。', 'The button came off.', '纽扣掉了。', ARRAY['ジッパー', '紐', '鍵']),
('N5', '手袋', 'てぶくろ', 'gloves', '手套', '冬は（　　）をします。', 'I wear gloves in winter.', '冬天戴手套。', ARRAY['帽子', '靴下', '指輪']),
('N5', '傘', 'かさ', 'umbrella', '伞', '雨が降っていますから、（　　）をさしましょう。', 'It''s raining, so let''s use an umbrella.', '下雨了，打伞吧。', ARRAY['帽子', '鞄', '靴']),
('N5', '荷物', 'にもつ', 'luggage/package', '行李/货物', '（　　）が届きました。', 'The package has arrived.', '货物到了。', ARRAY['便箋', '切手', '封筒']),
('N5', '箱', 'はこ', 'box', '箱子', '（　　）の中に何がありますか。', 'What is inside the box?', '箱子里有什么？', ARRAY['鞄', '机', '椅子']),
('N5', '棚', 'たな', 'shelf', '架子/橱', '（　　）の上に本を置きます。', 'I put books on the shelf.', '把书放在架子上。', ARRAY['箱', '机', '床']),
('N5', '机', 'つくえ', 'desk', '书桌', '（　　）の上で勉強します。', 'I study at the desk.', '在书桌下学习。', ARRAY['椅子', 'ベッド', 'ソファー']),
('N5', 'ベッド', 'べっど', 'bed', '床', '（　　）で寝ます。', 'I sleep on the bed.', '在床上睡觉。', ARRAY['机', '椅子', 'ソファー']),
('N5', 'ソファー', 'そふぁー', 'sofa', '沙发', '（　　）で休みましょう。', 'Let''s rest on the sofa.', '在沙发上休息吧。', ARRAY['ベッド', '椅子', '丸い']),
('N5', '石鹸', 'せっけん', 'soap', '肥皂/香皂', '（　　）で手を洗います。', 'I wash my hands with soap.', '用肥皂洗手。', ARRAY['シャンプー', '歯磨き', '水']),
('N5', '歯磨き', 'はみがき', 'toothpaste/brushing teeth', '刷牙/牙膏', '（　　）をしました。', 'I brushed my teeth.', '刷牙了。', ARRAY['洗顔', '洗濯', '掃除']),
('N5', 'お風呂', 'おふろ', 'bath', '洗澡/澡盆', '毎晩（　　）に入ります。', 'I take a bath every night.', '每天晚上泡澡。', ARRAY['プール', '海', 'シャワー']),
('N5', '夕飯', 'ゆうはん', 'evening meal/dinner', '晚饭', '（　　）の用意ができました。', 'Dinner is ready.', '晚饭准备好了。', ARRAY['昼食', '朝食', 'おやつ']),
('N5', 'お弁当', 'おべんとう', 'lunch box (bento)', '便当', '（　　）を作りました。', 'I made an bento.', '做了便当。', ARRAY['お菓子', 'ご飯', '果物']);
