-- Massive N5 Expansion - Batch 3 (Part 1: i-adjectives)
-- Includes Chinese Meaning and Sentence Translation

INSERT INTO vocabulary (level, word, reading, meaning, meaning_zh, sentence, sentence_translation, sentence_translation_zh, distractors) VALUES
('N5', '大きい', 'おおきい', 'big/large', '大', '（　　）鞄を買いました。', 'I bought a big bag.', '买了大的包。', ARRAY['小さい', '長い', '重い']),
('N5', '小さい', 'ちいさい', 'small/little', '小', '（　　）猫がいます。', 'There is a small cat.', '有一只小猫。', ARRAY['大きい', '短い', '軽い']),
('N5', '重い', 'おもい', 'heavy', '重', 'この荷物は（　　）です。', 'This luggage is heavy.', '这个行李很重。', ARRAY['軽い', '長い', '広い']),
('N5', '軽い', 'かるい', 'light (weight)', '轻', 'この鞄は（　　）です。', 'This bag is light.', '这个包变轻。', ARRAY['重い', '暗い', '早い']),
('N5', '新しい', 'あたらしい', 'new', '新', '（　　）家へ行きました。', 'I went to a new house.', '去了新家。', ARRAY['古い', '忙しい', '楽しい']),
('N5', '古い', 'ふるい', 'old', '旧/古', '（　　）時計を捨てました。', 'I threw away an old clock.', '扔了旧钟。', ARRAY['新しい', '遅い', '低い']),
('N5', '厚い', 'あつい', 'thick', '厚', '（　　）本を読みました。', 'I read a thick book.', '读了厚厚的书。', ARRAY['薄い', '熱い', '暑い']),
('N5', '薄い', 'うすい', 'thin', '薄', '（　　）紙をください。', 'Please give me some thin paper.', '请给我薄纸。', ARRAY['厚い', '広い', '狭い']),
('N5', '高い', 'たかい', 'expensive/high', '贵/高', 'この靴は（　　）です。', 'These shoes are expensive.', '这些鞋很贵。', ARRAY['安い', '低い', '短い']),
('N5', '安い', 'やすい', 'cheap', '便宜', '（　　）時計を買いました。', 'I bought a cheap watch.', '买了便宜的手表。', ARRAY['高い', '忙しい', '暗い']),
('N5', '低い', 'ひくい', 'low', '矮/低', '背が（　　）です。', 'He is short (height is low).', '个子矮。', ARRAY['高い', '長い', '広い']),
('N5', '長い', 'ながい', 'long', '长', '（　　）鉛筆を貸してください。', 'Please lend me a long pencil.', '请借我长铅笔。', ARRAY['短い', '低い', '広い']),
('N5', '短い', 'みじかい', 'short', '短', '（　　）休みがありました。', 'There was a short break.', '有短暂的休息。', ARRAY['長い', '重い', '高い']),
('N5', '広い', 'ひろい', 'spacious/wide', '宽/宽敞', '私の部屋は（　　）です。', 'My room is spacious.', '我的房间很宽敞。', ARRAY['狭い', '重い', '丸い']),
('N5', '狭い', 'せまい', 'narrow/small', '窄/狭窄', '道が（　　）です。', 'The road is narrow.', '路很窄。', ARRAY['広い', '明るい', '遠い']),
('N5', '早い', 'はやい', 'early/fast', '快/早', '（　　）時間に行きました。', 'I went early.', '早早去了。', ARRAY['遅い', '重い', '暗い']),
('N5', '遅い', 'おそい', 'late/slow', '晚/慢', '（　　）時間に帰りました。', 'I returned home late.', '很晚才回家。', ARRAY['早い', '新しい', '面白い']),
('N5', '暑い', 'あつい', 'hot (weather)', '热（天气）', '夏はとても（　　）です。', 'Summer is very hot.', '夏天非常热。', ARRAY['寒い', '涼しい', '暖かい']),
('N5', '寒い', 'さむい', 'cold (weather)', '冷（天气）', '冬はとても（　　）です。', 'Winter is very cold.', '冬天非常冷。', ARRAY['暑い', '暖かい', '冷たい']),
('N5', '熱い', 'あつい', 'hot (to touch)', '烫/热（触感）', '（　　）お茶を飲みます。', 'I drink hot tea.', '喝热茶。', ARRAY['冷たい', '涼しい', '白い']),
('N5', '冷たい', 'つめたい', 'cold (to touch)', '凉/冰（触感）', '（　　）水が飲みたいです。', 'I want to drink cold water.', '想喝凉水。', ARRAY['熱い', '暖かい', '暑い']),
('N5', '暖かい', 'あたたかい', 'warm (weather)', '暖和（天气）', '春は（　　）です。', 'Spring is warm.', '春天很暖和。', ARRAY['涼しい', '寒い', '冷たい']),
('N5', '涼しい', 'すずしい', 'cool (weather)', '凉快（天气）', '秋は（　　）ですね。', 'Autumn is cool, isn''t it?', '秋天很凉快。', ARRAY['暑い', '暖かい', '低い']),
('N5', '明るい', 'あかるい', 'bright', '明亮', '（　　）部屋で勉強しましょう。', 'Let''s study in a bright room.', '在明亮的房间学习吧。', ARRAY['暗い', '広い', '忙しい']),
('N5', '暗い', 'くらい', 'dark', '暗', '道が（　　）から、気をつけて。', 'The road is dark, so be careful.', '路很暗，小心点。', ARRAY['明るい', '白い', '赤い']),
('N5', '強い', 'つよい', 'strong', '强/有力', '（　　）風が吹いています。', 'A strong wind is blowing.', '刮着强风。', ARRAY['弱い', '太い', '長い']),
('N5', '弱い', 'よわい', 'weak', '弱/无力', '体が（　　）です。', 'The body is weak.', '身体虚弱。', ARRAY['強い', '太い', '細い']),
('N5', '太い', 'ふとい', 'thick/fat', '粗/胖', '（　　）鉛筆を買いました。', 'I bought a thick pencil.', '买了粗铅笔。', ARRAY['細い', '長い', '強い']),
('N5', '細い', 'ほそい', 'thin/slender', '细', '（　　）道を行きました。', 'I went down a thin path.', '走了细路。', ARRAY['太い', '短い', '広い']),
('N5', '丸い', 'まるい', 'round', '圆', '（　　）テーブルがあります。', 'There is a round table.', '有个圆桌。', ARRAY['四角い', '長い', '広い']),
('N5', '良い', 'よい/いい', 'good', '好', '今日は（　　）天気です。', 'It''s a good weather today.', '今天天气很好。', ARRAY['悪い', '遅い', '暗い']),
('N5', '悪い', 'わるい', 'bad', '坏/不好', '気分が（　　）です。', 'I feel bad (the mood is bad).', '心情不好。', ARRAY['良い', '広い', '短い']),
('N5', '忙しい', 'いそがしい', 'busy', '忙', '今日はとても（　　）です。', 'I am very busy today.', '今天非常忙。', ARRAY['暇', '楽しい', '面白い']),
('N5', '暇', 'ひま', 'free (time)', '闲/有空', '（　　）な時に本を読みます。', 'I read books when I''m free.', '有空时看书。', ARRAY['忙しい', '賑やか', '好き']),
('N5', '楽しい', 'たのしい', 'fun/enjoyable', '快乐/开心', '（　　）旅行でした。', 'It was a fun trip.', '是很开心的旅行。', ARRAY['忙しい', '辛い', '古い']),
('N5', '面白い', 'おもしろい', 'interesting/funny', '有趣/搞笑', '（　　）映画を見ました。', 'I saw an interesting movie.', '看了有趣的电影。', ARRAY['詰まらない', '難しい', '新しい']),
('N5', '詰まらない', 'つまらない', 'boring', '无聊/没意思', 'この本は（　　）です。', 'This book is boring.', '这本书很枯燥。', ARRAY['面白い', '楽しい', '新しい']),
('N5', '難しい', 'むずかしい', 'difficult', '难', '日本語は（　　）ですか。', 'Is Japanese difficult?', '日语难吗？', ARRAY['易しい', '面白い', '早い']),
('N5', '易しい', 'やさしい', 'easy', '容易/简单', '試験は（　　）かったです。', 'The exam was easy.', '考试很简单。', ARRAY['難しい', '厳しい', '面白い']),
('N5', '上手', 'じょうず', 'skillful/good at', '擅长/好', '料理が（　　）ですね。', 'You are good at cooking, aren''t you?', '你做菜很好吃吧。', ARRAY['下手', '下手(したて)', '上手(うわて)']),
('N5', '下手', 'へた', 'unskillful/bad at', '不擅长/笨拙', 'テニスが（　　）です。', 'I am bad at tennis.', '我不擅长打网球。', ARRAY['上手', '得意', '得意(とくい)']),
('N5', '好き', 'すき', 'like/lovely', '喜欢', 'りんごが（　　）です。', 'I like apples.', '喜欢苹果。', ARRAY['嫌い', '嫌(いや)', '上手']),
('N5', '嫌い', 'きらい', 'dislike/hate', '讨厌', '野菜が（　　）です。', 'I dislike vegetables.', '讨厌蔬菜。', ARRAY['好き', '上手', '下手']),
('N5', '美味しい', 'おいしい', 'delicious', '美味/好吃', 'このお菓子は（　　）です。', 'This sweet is delicious.', '这种点心很好吃。', ARRAY['不味い', '甘い', '辛い']),
('N5', '不味い', 'まずい', 'tastes bad', '难吃', 'この料理は（　　）です。', 'This dish tastes bad.', '这道菜很难吃。', ARRAY['美味しい', '苦い', '甘い']),
('N5', '甘い', 'あまい', 'sweet', '甜', 'この果物はとても（　　）です。', 'This fruit is very sweet.', '这个水果非常甜。', ARRAY['辛い', '苦い', '酸っぱい']),
('N5', '辛い', 'からい', 'spicy/hot', '辣', '（　　）カレーを食べました。', 'I ate spicy curry.', '吃了辣咖喱。', ARRAY['甘い', '塩辛い', '苦い']),
('N5', '塩辛い', 'しおからい', 'salty', '咸', 'スープが少し（　　）です。', 'The soup is a little salty.', '汤有点咸。', ARRAY['甘い', '苦い', '酸っぱい']),
('N5', '苦い', 'にがい', 'bitter', '苦', '（　　）コーヒーが好きです。', 'I like bitter coffee.', '喜欢苦咖啡。', ARRAY['甘い', '辛い', '美味しい']),
('N5', '酸っぱい', 'すっぱい', 'sour', '酸', 'このレモンは（　　）です。', 'This lemon is sour.', '这个柠檬很酸。', ARRAY['甘い', '辛い', '塩辛い']);
