-- Massive N5 Expansion - Batch 2 (Part 2: Places & Directions)
-- Includes Chinese Meaning and Sentence Translation

INSERT INTO vocabulary (level, word, reading, meaning, meaning_zh, sentence, sentence_translation, sentence_translation_zh, distractors) VALUES
('N5', '銀行', 'ぎんこう', 'bank', '银行', '（　　）へお金を出しに行きます。', 'I am going to the bank to withdraw money.', '去银行取钱。', ARRAY['郵便局', '病院', '映画館']),
('N5', '郵便局', 'ゆうびんきょく', 'post office', '邮局', '（　　）で切手を買います。', 'I buy stamps at the post office.', '在邮局买邮票。', ARRAY['銀行', '図書館', '駅']),
('N5', '病院', 'びょういん', 'hospital', '医院', '風邪を引いたので、（　　）へ行きます。', 'I have a cold, so I am going to the hospital.', '因为感冒了，去医院。', ARRAY['美容院', '映画館', '学校']),
('N5', '駅', 'えき', 'station', '车站', '（　　）の前で待ちましょう。', 'Let''s wait in front of the station.', '在车站前等吧。', ARRAY['公園', '学校', '家']),
('N5', '映画館', 'えいがかん', 'movie theater', '电影院', '（　　）で新しい映画を見ました。', 'I saw a new movie at the movie theater.', '在电影院看了新电影。', ARRAY['図書館', '美術館', '体育館']),
('N5', '図書館', 'としょかん', 'library', '图书馆', '（　　）で本を借ります。', 'I borrow books at the library.', '在图书馆借书。', ARRAY['本屋', '学校', '駅']),
('N5', '本屋', 'ほんや', 'bookstore', '书店', '（　　）で辞書を買いました。', 'I bought a dictionary at the bookstore.', '在书店买了词典。', ARRAY['図書館', '花屋', '肉屋']),
('N5', '花屋', 'はなや', 'flower shop', '花店', '（　　）で綺麗な花を買いました。', 'I bought beautiful flowers at the flower shop.', '在花店买了漂亮的花。', ARRAY['八百屋', '本屋', '魚屋']),
('N5', '店', 'みせ', 'shop/store', '店', 'この（　　）はいつも忙しいです。', 'This shop is always busy.', '这家店一直很忙。', ARRAY['家', '部屋', '庭']),
('N5', '喫茶店', 'きっさてん', 'coffee shop/cafe', '咖啡馆', '（　　）でコーヒーを飲みましょう。', 'Let''s drink coffee at the coffee shop.', '在咖啡店喝咖啡吧。', ARRAY['レストラン', 'デパート', '食堂']),
('N5', 'レストラン', 'れすとらん', 'restaurant', '餐厅/饭馆', '今日の晩ご飯は（　　）で食べます。', 'I will eat dinner at a restaurant today.', '今天晚饭在餐厅吃。', ARRAY['食堂', '喫茶店', '家']),
('N5', '食堂', 'しょくどう', 'cafeteria/dining hall', '食堂', '学校の（　　）は安くて美味しいです。', 'The school cafeteria is cheap and delicious.', '学校食堂又便宜又好吃。', ARRAY['レストラン', '喫茶店', '教室']),
('N5', 'デパート', 'でぱーと', 'department store', '百货商店', '日曜日、（　　）へ買い物に行きました。', 'On Sunday, I went to the department store for shopping.', '周日去百货店买东西了。', ARRAY['スーパー', 'コンビニ', '薬局']),
('N5', 'スーパー', 'すーぱー', 'supermarket', '超市', '（　　）で野菜を買いましょう。', 'Let''s buy vegetables at the supermarket.', '在超市买蔬菜吧。', ARRAY['デパート', 'コンビニ', '喫茶店']),
('N5', 'コンビニ', 'こんびに', 'convenience store', '便利店', '夜、（　　）でお弁当を買いました。', 'At night, I bought a lunch box at the convenience store.', '晚上在便利店买了便当。', ARRAY['スーパー', 'デパート', '郵便局']),
('N5', '薬局', 'やっきょく', 'pharmacy/drugstore', '药店', '（　　）で薬を買いました。', 'I bought medicine at the pharmacy.', '在药店买了药。', ARRAY['病院', '美容院', '肉屋']),
('N5', '交番', 'こうばん', 'police box', '交番/派出所', '道がわからないので、（　　）で聞きました。', 'I didn''t know the way, so I asked at the police box.', '因为不认识路，在派出所问了。', ARRAY['役所', '消防署', '駅']),
('N5', '公園', 'こうえん', 'park', '公园', '（　　）で散歩をしましょう。', 'Let''s take a walk in the park.', '在公园散步吧。', ARRAY['庭', '学校', '駅']),
('N5', '海', 'うみ', 'sea/ocean', '海', '夏休みに（　　）へ行きたいです。', 'I want to go to the sea during summer vacation.', '暑假想去海边。', ARRAY['山', '川', '池']),
('N5', '山', 'やま', 'mountain', '山', '（　　）に登ります。', 'I will climb the mountain.', '爬山。', ARRAY['海', '空', '街']),
('N5', '川', 'かわ', 'river', '河/川', 'この（　　）はとても綺麗です。', 'This river is very beautiful.', '这条河非常漂亮。', ARRAY['池', '海', '森']),
('N5', '池', 'いけ', 'pond', '池塘', '（　　）に魚がいます。', 'There are fish in the pond.', '池塘里有鱼。', ARRAY['海', '川', '井戸']),
('N5', '森', 'もり', 'forest', '森林', '（　　）の中に鳥がいます。', 'There are birds in the forest.', '森林里有鸟。', ARRAY['林', '山', '畑']),
('N5', '空', 'そら', 'sky', '天空', '（　　）が青いです。', 'The sky is blue.', '天很蓝。', ARRAY['雲', '星', '月']),
('N5', '上', 'うえ', 'up/above', '上', '本箱の（　　）に鞄があります。', 'There is a bag on top of the bookcase.', '书架上面有包。', ARRAY['下', '中', '横']),
('N5', '下', 'した', 'down/below', '下', '机の（　　）に猫がいます。', 'There is a cat under the desk.', '桌子下面有猫。', ARRAY['上', '中', '前']),
('N5', '中', 'なか', 'inside', '里/中', '鞄の（　　）に財布があります。', 'There is a wallet inside the bag.', '包里有钱包。', ARRAY['外', '横', '奥']),
('N5', '外', 'そと', 'outside', '外面', '（　　）に遊びに行きましょう。', 'Let''s go outside to play.', '去外面玩吧。', ARRAY['中', '内', '横']),
('N5', '前', 'まえ', 'front', '前', '駅の（　　）にバス停があります。', 'There is a bus stop in front of the station.', '车站前面有公交站。', ARRAY['後ろ', '隣', '横']),
('N5', '後ろ', 'うしろ', 'back/behind', '后面', '私の（　　）に誰かがいます。', 'Someone is behind me.', '我后面有人。', ARRAY['前', '隣', '中']),
('N5', '左', 'ひだり', 'left', '左', '（　　）に曲がってください。', 'Please turn left.', '请向左转。', ARRAY['右', '北', '南']),
('N5', '右', 'みぎ', 'right', '右', '（　　）へ行ってください。', 'Please go to the right.', '请往右走。', ARRAY['左', '上', '下']),
('N5', '隣', 'となり', 'next to', '旁边/隔壁', '（　　）の部屋に誰かいますか。', 'Is there someone in the next room?', '隔壁房间有人吗？', ARRAY['近く', '遠く', '間']),
('N5', '近く', 'ちかく', 'near', '附近', '駅の（　　）に住んでいます。', 'I live near the station.', '住在车站附近。', ARRAY['遠く', '広い', '狭い']),
('N5', '遠く', 'とおく', 'far', '远', 'ここから（　　）に山が見えます。', 'I can see mountains far from here.', '从这能看到远处的山。', ARRAY['近く', 'すぐ', '隣']),
('N5', '間', 'あいだ', 'between', '之间', '銀行と郵便局の（　　）にあります。', 'It is between the bank and the post office.', '在银行和邮局之间。', ARRAY['中', '横', '側']),
('N5', '向こう', 'むこう', 'opposite side', '对面', '（　　）にビルがあります。', 'There is a building on the opposite side.', '对面有一栋楼。', ARRAY['こちら', 'そちら', 'あちら']),
('N5', 'こちら', 'こちら', 'this way', '这边', '（　　）へどうぞ。', 'This way, please.', '请往这边走。', ARRAY['そちら', 'あちら', 'どちら']),
('N5', '北', 'きた', 'north', '北', '（　　）の方は寒いです。', 'It is cold in the north.', '北方很冷。', ARRAY['南', '東', '西']),
('N5', '南', 'みなみ', 'south', '南', '（　　）へ行くと海があります。', 'There is the sea if you go south.', '往南走有海。', ARRAY['北', '東', '西']),
('N5', '東', 'ひがし', 'east', '东', '太陽は（　　）から出ます。', 'The sun rises from the east.', '太阳从东方升起。', ARRAY['西', '南', '北']),
('N5', '西', 'にし', 'west', '西', '（　　）へ太陽が沈みます。', 'The sun sets in the west.', '太阳往西方落下。', ARRAY['東', '南', '北']),
('N5', '出口', 'でぐち', 'exit', '出口', '（　　）はどこですか。', 'Where is the exit?', '出口在哪？', ARRAY['入口', '窓', '門']),
('N5', '入口', 'いりぐち', 'entrance', '入口', '（　　）で待ってください。', 'Please wait at the entrance.', '请在入口等。', ARRAY['出口', '外', '中']),
('N5', '建物', 'たてもの', 'building', '建筑物/楼', '高い（　　）が見えます。', 'I can see a tall building.', '能看到高楼。', ARRAY['公園', '広場', '道']),
('N5', '道', 'みち', 'road/path', '路', '（　　）をまっすぐ行ってください。', 'Please go straight down the road.', '请沿着这条路直走。', ARRAY['空', '海', '庭']),
('N5', '橋', 'はし', 'bridge', '桥', '（　　）を渡ります。', 'I cross the bridge.', '过桥。', ARRAY['道', '階段', '坂']),
('N5', '地図', 'ちず', 'map', '地图', '（　　）を書いてください。', 'Please draw a map.', '请画张地图。', ARRAY['絵', '字', '写真']),
('N5', '住所', 'じゅうしょ', 'address', '地址', '（　　）を教えてください。', 'Please tell me your address.', '请告诉我你的地址。', ARRAY['名まえ', '番号', '仕事']),
('N5', '番号', 'ばんごう', 'number', '号码', '電話（　　）は何番ですか。', 'What is your phone number?', '电话号码是多少？', ARRAY['住所', '生年月日', '名前']);
